class OAuth2Error(Exception):
    pass
